################################################################
#### ####
################################################################
version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: aloxatel/langbrainscore
    docker:
      - image: circleci/buildpack-deps:stretch


################################################################
#### definitions of jobs ####
################################################################
jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false # not allowed in free tier
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:latest .
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  publish-latest:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker:
          docker_layer_caching: false # not allowed in free tier
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest
  docs-build:
    docker:
      - image: aloxatel/langbrainscore
    steps:
      - checkout
      - run:
          name: Build docs
          command: |
#            poetry shell
            pdoc3 --html langbrainscore --force 
      - persist_to_workspace:
          root: html/langbrainscore
          paths: '*'
  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: html
      - add_ssh_keys:
          fingerprints:
            - "69:08:74:89:7c:dd:ed:e2:e3:a8:85:3b:73:3d:dd:24"
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "pdoc3@circleci.com"
            git config user.name "asathe"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dotfiles --message "[skip ci] Docs updates" --dist html

################################################################
#### definitions of workflows ####
################################################################
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: circle-ci
      - publish-latest:
          requires:
            - build
          filters:
            branches:
              only: circle-ci
      - docs-build:
          filters:
            branches:
              only: main
      - docs-deploy:
          requires:
            - docs-build
          filters:
            branches:
              only: main
